// Generated by gencpp from file Assignment2_Turtlesim/MakeCircleRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLEREQUEST_H
#define ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Assignment2_Turtlesim
{
template <class ContainerAllocator>
struct MakeCircleRequest_
{
  typedef MakeCircleRequest_<ContainerAllocator> Type;

  MakeCircleRequest_()
    : s(0.0)
    , r(0.0)  {
    }
  MakeCircleRequest_(const ContainerAllocator& _alloc)
    : s(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef float _s_type;
  _s_type s;

   typedef float _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MakeCircleRequest_

typedef ::Assignment2_Turtlesim::MakeCircleRequest_<std::allocator<void> > MakeCircleRequest;

typedef boost::shared_ptr< ::Assignment2_Turtlesim::MakeCircleRequest > MakeCircleRequestPtr;
typedef boost::shared_ptr< ::Assignment2_Turtlesim::MakeCircleRequest const> MakeCircleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Assignment2_Turtlesim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d766f6a2db01255c7ae96df4f8888c5";
  }

  static const char* value(const ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d766f6a2db01255ULL;
  static const uint64_t static_value2 = 0xc7ae96df4f8888c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Assignment2_Turtlesim/MakeCircleRequest";
  }

  static const char* value(const ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 s\n\
float32 r\n\
\n\
";
  }

  static const char* value(const ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MakeCircleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Assignment2_Turtlesim::MakeCircleRequest_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<float>::stream(s, indent + "  ", v.s);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLEREQUEST_H
