// Generated by gencpp from file Assignment2_Turtlesim/MakeCircle.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLE_H
#define ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLE_H

#include <ros/service_traits.h>


#include <Assignment2_Turtlesim/MakeCircleRequest.h>
#include <Assignment2_Turtlesim/MakeCircleResponse.h>


namespace Assignment2_Turtlesim
{

struct MakeCircle
{

typedef MakeCircleRequest Request;
typedef MakeCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakeCircle
} // namespace Assignment2_Turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Assignment2_Turtlesim::MakeCircle > {
  static const char* value()
  {
    return "6d766f6a2db01255c7ae96df4f8888c5";
  }

  static const char* value(const ::Assignment2_Turtlesim::MakeCircle&) { return value(); }
};

template<>
struct DataType< ::Assignment2_Turtlesim::MakeCircle > {
  static const char* value()
  {
    return "Assignment2_Turtlesim/MakeCircle";
  }

  static const char* value(const ::Assignment2_Turtlesim::MakeCircle&) { return value(); }
};


// service_traits::MD5Sum< ::Assignment2_Turtlesim::MakeCircleRequest> should match 
// service_traits::MD5Sum< ::Assignment2_Turtlesim::MakeCircle > 
template<>
struct MD5Sum< ::Assignment2_Turtlesim::MakeCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Assignment2_Turtlesim::MakeCircle >::value();
  }
  static const char* value(const ::Assignment2_Turtlesim::MakeCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Assignment2_Turtlesim::MakeCircleRequest> should match 
// service_traits::DataType< ::Assignment2_Turtlesim::MakeCircle > 
template<>
struct DataType< ::Assignment2_Turtlesim::MakeCircleRequest>
{
  static const char* value()
  {
    return DataType< ::Assignment2_Turtlesim::MakeCircle >::value();
  }
  static const char* value(const ::Assignment2_Turtlesim::MakeCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Assignment2_Turtlesim::MakeCircleResponse> should match 
// service_traits::MD5Sum< ::Assignment2_Turtlesim::MakeCircle > 
template<>
struct MD5Sum< ::Assignment2_Turtlesim::MakeCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Assignment2_Turtlesim::MakeCircle >::value();
  }
  static const char* value(const ::Assignment2_Turtlesim::MakeCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Assignment2_Turtlesim::MakeCircleResponse> should match 
// service_traits::DataType< ::Assignment2_Turtlesim::MakeCircle > 
template<>
struct DataType< ::Assignment2_Turtlesim::MakeCircleResponse>
{
  static const char* value()
  {
    return DataType< ::Assignment2_Turtlesim::MakeCircle >::value();
  }
  static const char* value(const ::Assignment2_Turtlesim::MakeCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT2_TURTLESIM_MESSAGE_MAKECIRCLE_H
