// Generated by gencpp from file assignment_2/MakeCircle.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_MESSAGE_MAKECIRCLE_H
#define ASSIGNMENT_2_MESSAGE_MAKECIRCLE_H

#include <ros/service_traits.h>


#include <assignment_2/MakeCircleRequest.h>
#include <assignment_2/MakeCircleResponse.h>


namespace assignment_2
{

struct MakeCircle
{

typedef MakeCircleRequest Request;
typedef MakeCircleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakeCircle
} // namespace assignment_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2::MakeCircle > {
  static const char* value()
  {
    return "6d766f6a2db01255c7ae96df4f8888c5";
  }

  static const char* value(const ::assignment_2::MakeCircle&) { return value(); }
};

template<>
struct DataType< ::assignment_2::MakeCircle > {
  static const char* value()
  {
    return "assignment_2/MakeCircle";
  }

  static const char* value(const ::assignment_2::MakeCircle&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2::MakeCircleRequest> should match 
// service_traits::MD5Sum< ::assignment_2::MakeCircle > 
template<>
struct MD5Sum< ::assignment_2::MakeCircleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2::MakeCircle >::value();
  }
  static const char* value(const ::assignment_2::MakeCircleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2::MakeCircleRequest> should match 
// service_traits::DataType< ::assignment_2::MakeCircle > 
template<>
struct DataType< ::assignment_2::MakeCircleRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2::MakeCircle >::value();
  }
  static const char* value(const ::assignment_2::MakeCircleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2::MakeCircleResponse> should match 
// service_traits::MD5Sum< ::assignment_2::MakeCircle > 
template<>
struct MD5Sum< ::assignment_2::MakeCircleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2::MakeCircle >::value();
  }
  static const char* value(const ::assignment_2::MakeCircleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2::MakeCircleResponse> should match 
// service_traits::DataType< ::assignment_2::MakeCircle > 
template<>
struct DataType< ::assignment_2::MakeCircleResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2::MakeCircle >::value();
  }
  static const char* value(const ::assignment_2::MakeCircleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_MESSAGE_MAKECIRCLE_H
